name: hostelfinder
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# Dart SDK version compatibility
environment:
  sdk: '>=3.4.3 <4.0.0'

# Flutter dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  carousel_slider: ^5.0.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  fluttertoast: ^8.2.6
  firebase_database: ^11.0.2
  firebase_storage: ^12.1.0
  http: ^1.2.1
  firebase_core_dart: ^1.0.1
  url_launcher: ^6.3.0
  animated_bottom_navigation_bar: ^1.3.3
  image_picker: ^0.8.5+3
  cloud_firestore: ^5.1.0
  file_picker: ^8.0.6
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.4
  webview_flutter: ^4.8.0
  google_maps_flutter: ^2.7.0
  geolocator: ^13.0.1
  animated_text_kit: ^4.2.2
  folding_cell: ^1.0.2
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  convex_bottom_bar: ^3.2.0
  twilio_flutter: ^0.9.0
  cloud_functions: ^5.1.2
  flutter_sms: ^2.3.3
# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/

# Uncomment this section if you want to add custom fonts
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
