// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVe_vZji0v9WZb3F0RLJP2aik096lY6yA',
    appId: '1:590911637894:web:415461bc808880e21ec407',
    messagingSenderId: '590911637894',
    projectId: 'fir-926e3',
    authDomain: 'fir-926e3.firebaseapp.com',
    storageBucket: 'fir-926e3.appspot.com',
    measurementId: 'G-HLT8Z6XM7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiWloTpsA-eS6GzMf1N4qjUt7uF3k3LOo',
    appId: '1:590911637894:android:45ed172cef59fee51ec407',
    messagingSenderId: '590911637894',
    projectId: 'fir-926e3',
    storageBucket: 'fir-926e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYNHsk5CvD_KJWYHqR_ajgX8Js5CPoBF4',
    appId: '1:590911637894:ios:4bb42cff48ac44a91ec407',
    messagingSenderId: '590911637894',
    projectId: 'fir-926e3',
    storageBucket: 'fir-926e3.appspot.com',
    iosBundleId: 'com.example.hostelfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYNHsk5CvD_KJWYHqR_ajgX8Js5CPoBF4',
    appId: '1:590911637894:ios:4bb42cff48ac44a91ec407',
    messagingSenderId: '590911637894',
    projectId: 'fir-926e3',
    storageBucket: 'fir-926e3.appspot.com',
    iosBundleId: 'com.example.hostelfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVe_vZji0v9WZb3F0RLJP2aik096lY6yA',
    appId: '1:590911637894:web:1989746970e5084f1ec407',
    messagingSenderId: '590911637894',
    projectId: 'fir-926e3',
    authDomain: 'fir-926e3.firebaseapp.com',
    storageBucket: 'fir-926e3.appspot.com',
    measurementId: 'G-VX96SYJGDB',
  );
}
